apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: {{ image }}
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: db
            - name: DB_DATABASE
              value: larademo
            - name: DB_USERNAME
              value: rajiv
            - name: DB_PASSWORD
              value: "1234"  
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: laravel-service
# spec:
#   #type: NodePort
#   type: ClusterIP
#   selector:
#     app: laravel
#   ports:
#     - port: 80
#       #targetPort: 9000
#       #nodePort: 30080

apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

