apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  #we can use LoadBalancer instead of NodePort if we are on EKS/GKE/AKS.
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 9000
